name: Generate ASCII Artwork

on:  
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
    -  name: Added Checkout
       uses: actions/checkout@v4   

        

    - name: Excecuting shell script
      run: |
       chmod +x ascii-script.sh
       ./ascii-script.sh
