name: Generate ASCII Artwork

on:  
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest

    steps:
    -  name: Added Checkout
       uses: actions/checkout@v4   

        

    - name: Excecuting shell script
      run: |
       chmod +x shell-ascii.sh
       ./shell-ascii.sh
