name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        -  name: Added Checkout
           uses: actions/checkout@v4    

        -  name: Welcome Message
           run: echo "Welcome back"

        -  name: list files
           run: ls

        -  name: View file 
           run: cat README.md
